#!/usr/bin/env python3
"""Generate the Core 0.1 dependency-derived teaching-layer report."""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from audit_core_dependency_inventory import (  # noqa: E402
    INVENTORY_PATH,
    derive_layers,
    load_inventory,
    validate_inventory,
)

OUTPUT_PATH = Path(
    "docs/dependency-map/generated/CORE_0.1_DERIVED_TEACHING_ORDER.md"
)
BT = chr(96)


def render(root: Path) -> str:
    data = load_inventory(root)
    errors = validate_inventory(data, root)
    if errors:
        raise ValueError(
            "dependency inventory validation failed before generation:\n"
            + "\n".join(f"- {error}" for error in errors)
        )

    layers, cyclic_nodes = derive_layers(data)
    if cyclic_nodes:
        raise ValueError(
            "cannot generate teaching layers from cyclic constraints: "
            + ", ".join(cyclic_nodes)
        )

    nodes = {node["id"]: node for node in data["nodes"]}
    edges = data["edges"]

    incoming: dict[str, list[dict[str, object]]] = defaultdict(list)
    for edge in edges:
        if edge["order_constraint"] is True:
            incoming[edge["to"]].append(edge)

    class_counts = Counter(edge["class"] for edge in edges)
    basis_counts = Counter(edge["basis"] for edge in edges)

    lines: list[str] = []
    lines.append("# Core 0.1 Dependency-Derived Teaching Layers")
    lines.append("")
    lines.append(
        "> Generated from "
        + BT
        + INVENTORY_PATH.as_posix()
        + BT
        + ". Do not edit this file independently."
    )
    lines.append("")
    lines.append("**Status:** provisional research evidence; this artifact does not independently establish E1, E2, or E3 PASS")
    lines.append("")
    lines.append(data["authority_note"])
    lines.append("")
    lines.append("## Derivation policy")
    lines.append("")
    lines.append(
        "- HARD and STRONG edges constrain the topological layers."
    )
    lines.append(
        "- SUPPORTING and HISTORICAL/CURRICULAR edges remain documented but "
        "do not force layer order."
    )
    lines.append(
        "- NONE relationships remain separate non-dependency observations."
    )
    lines.append(
        "- A layer means only that the current inventory contains no "
        "constraining edge requiring one node in that layer to follow another."
    )
    lines.append(
        "- Layer 0 does not mean globally prerequisite-free. Declared source "
        "gaps are preserved rather than silently filled."
    )
    lines.append("")
    lines.append("## Inventory summary")
    lines.append("")
    lines.append(
        f"- Teaching-layer nodes: {sum(1 for node in nodes.values() if node['include_in_teaching_layers'])}"
    )
    lines.append(f"- Classified dependency edges: {len(edges)}")
    lines.append(
        f"- Constraining edges: {sum(1 for edge in edges if edge['order_constraint'])}"
    )
    lines.append(f"- HARD edges: {class_counts['HARD']}")
    lines.append(f"- STRONG edges: {class_counts['STRONG']}")
    lines.append(f"- SUPPORTING edges: {class_counts['SUPPORTING']}")
    lines.append(
        f"- HISTORICAL/CURRICULAR edges: {class_counts['HISTORICAL/CURRICULAR']}"
    )
    lines.append(
        f"- Explicit non-dependency observations: {len(data['non_dependencies'])}"
    )
    lines.append(f"- Derived topological layers: {len(layers)}")
    lines.append("")
    lines.append("Source-basis counts:")
    lines.append("")
    for basis in sorted(basis_counts):
        lines.append(f"- {basis}: {basis_counts[basis]}")
    lines.append("")
    lines.append("## Candidate topological layers")
    lines.append("")
    lines.append(
        "These layers are mechanically derived from the current HARD and "
        "STRONG edge set."
    )
    lines.append("")

    declared_roots = {
        item["node"]: item for item in data["declared_roots"]
    }

    for index, layer in enumerate(layers):
        lines.append(f"### Layer {index}")
        lines.append("")
        for node_id in sorted(layer, key=lambda item: nodes[item]["label"].lower()):
            node = nodes[node_id]
            label = node["label"]
            family = node["family"]
            predecessors = sorted(
                incoming.get(node_id, []),
                key=lambda edge: nodes[edge["from"]]["label"].lower(),
            )

            if predecessors:
                pred_text = "; ".join(
                    f"{nodes[edge['from']]['label']} [{edge['class']}]"
                    for edge in predecessors
                )
                lines.append(
                    f"- **{label}** ({BT}{node_id}{BT}) — {family}. "
                    f"Constraining predecessors: {pred_text}."
                )
            else:
                root = declared_roots[node_id]
                lines.append(
                    f"- **{label}** ({BT}{node_id}{BT}) — {family}. "
                    f"Declared root: {root['kind']}."
                )
        lines.append("")

    lines.append("## Declared roots")
    lines.append("")
    lines.append("| Node | Root kind | Rationale |")
    lines.append("|---|---|---|")
    for item in data["declared_roots"]:
        label = nodes[item["node"]]["label"]
        lines.append(
            f"| {label} | {item['kind']} | {item['rationale']} |"
        )
    lines.append("")

    lines.append("## Open dependency questions")
    lines.append("")
    for item in data["open_questions"]:
        related = ", ".join(nodes[node_id]["label"] for node_id in item["related_nodes"])
        lines.append(
            f"- **{item['id']} — {item['question']}** Related nodes: {related}. "
            f"Reason: {item['reason']}"
        )
    lines.append("")

    lines.append("## Non-constraining classified edges")
    lines.append("")
    lines.append("| From | To | Class | Basis | Rationale |")
    lines.append("|---|---|---|---|---|")
    for edge in sorted(
        (edge for edge in edges if not edge["order_constraint"]),
        key=lambda edge: (nodes[edge["from"]]["label"], nodes[edge["to"]]["label"]),
    ):
        lines.append(
            f"| {nodes[edge['from']]['label']} | {nodes[edge['to']]['label']} | "
            f"{edge['class']} | {edge['basis']} | {edge['rationale']} |"
        )
    lines.append("")

    lines.append("## Explicit non-dependencies")
    lines.append("")
    lines.append("| From | To | Result | Rationale |")
    lines.append("|---|---|---|---|")
    for item in data["non_dependencies"]:
        lines.append(
            f"| {nodes[item['from']]['label']} | {nodes[item['to']]['label']} | "
            f"{item['result']} | {item['rationale']} |"
        )
    lines.append("")

    lines.append("## Interpretation limits")
    lines.append("")
    lines.append(
        "This report is a deterministic projection of the current inventory, "
        "not a claim that the inventory is complete or that the resulting "
        "layers are the final curriculum."
    )
    lines.append(
        "In particular, unresolved cross-branch dependencies can move nodes "
        "to later layers. The open questions above are therefore part of the "
        "result, not defects to hide."
    )
    lines.append("")
    lines.append("## Reproduction")
    lines.append("")
    lines.append("From the repository root:")
    lines.append("")
    lines.append(BT * 3 + "bash")
    lines.append("python scripts/audit_core_dependency_inventory.py")
    lines.append("python scripts/audit_core_dependency_inventory.py --self-test")
    lines.append("python scripts/generate_core_dependency_order.py --check")
    lines.append(BT * 3)
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed generated report differs from the inventory.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the generated report without writing it.",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    expected = render(root)
    output = root / OUTPUT_PATH

    if args.stdout:
        print(expected, end="")
        return 0

    if args.check:
        if not output.is_file():
            print(f"generated report is missing: {OUTPUT_PATH.as_posix()}")
            return 1
        actual = output.read_text(encoding="utf-8")
        if actual != expected:
            print(
                "generated report is stale; run "
                "python scripts/generate_core_dependency_order.py"
            )
            return 1
        print("generated_report_current=1")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
